# Generated by Django 3.1.6 on 2021-03-07 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_custompermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'DATA_PROCESSING'), (2, 'ANOMALY_DETECTION')])),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN_PROGRESS'), (3, 'OK'), (4, 'BAD_REQUEST'), (5, 'WORKER_TIMEOUT'), (6, 'QUEUE_TIMEOUT'), (7, 'SUPPLIER_ERROR'), (8, 'ERROR')], default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(null=True, db_index=True)),
                ('last_edited_datetime', models.DateTimeField(auto_now=True)),
                ('finish_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
