# Generated by Django 3.1.6 on 2021-03-26 14:29

from django.db import migrations, models
import django.db.models.deletion

from persistence.models import CustomUser, Patient


def create_default_patient(apps, schema_editor):
    user = CustomUser.objects.create_user(email="default@default.com",
                                          phone_number=12345678910,
                                          password="password",
                                          type="PT")
    user.save()
    patient = Patient.objects.create(first_name="John", last_name="Smith", date_of_birth="1998-03-03",
                                     height_cm=188, weight_kg=98, patient_account=user)
    patient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.BigIntegerField()),
                ('finish_time', models.BigIntegerField()),
                ('file', models.FileField(upload_to='file_storage/')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='persistence.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.patient')),
                ('raw_recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persistence.rawrecording')),
            ],
        ),
        migrations.RunPython(create_default_patient),
    ]
