# Generated by Django 3.1.6 on 2021-03-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persistence', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.BigIntegerField()),
                ('finish_time', models.BigIntegerField()),
                ('file', models.FileField(upload_to='file_storage/')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='patient', to='persistence.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('feedback', models.TextField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='activity_results',
                                              to='persistence.patient')),
                ('raw_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='activity_result',
                                                    to='persistence.rawrecording')),
            ],
        ),
    ]
