# Generated by Django 3.1.6 on 2021-04-07 21:41

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.models import Group
from django.db import migrations, models

from persistence.models import Patient, CustomUser


def create_default_patient(apps, schema_editor):
    user = CustomUser.objects.create_user(email="default@default.com",
                                          phone_number=12345678910,
                                          password="password",
                                          user_type="PT",
                                          family_members=None,
                                          assigned_patients=None,
                                          assigned_practitioner_id=None)
    user.save()
    patient_group = Group.objects.get(name="PATIENT")
    patient_group.user_set.add(user)
    patient = Patient.objects.create(first_name="John", last_name="Smith",
                                     date_of_birth="1998-03-03", height_cm=188, weight_kg=98,
                                     patient_account=user)
    patient.save()


def create_default_practitioner(apps, schema_editor):
    practitioner_1 = CustomUser.objects.create_user(email="default@practitioner.com",
                                                    phone_number=11111111111,
                                                    password="password",
                                                    user_type="PR",
                                                    family_members=None,
                                                    assigned_patients=None,
                                                    assigned_practitioner_id=None)
    practitioner_1.save()
    practitioner_2 = CustomUser.objects.create_user(email="other@practitioner.com",
                                                    phone_number=11111111123,
                                                    password="password",
                                                    user_type="PR",
                                                    family_members=None,
                                                    assigned_patients=None,
                                                    assigned_practitioner_id=None)
    practitioner_2.save()
    practitioner_group = Group.objects.get(name="PRACTITIONER")
    practitioner_group.user_set.add(practitioner_1)


class Migration(migrations.Migration):
    dependencies = [
        ('persistence', '0006_auto_20210330_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='assigned_patients', to='persistence.customuser',
                                    null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='family_members',
            field=models.ManyToManyField(related_name='relatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_default_patient),
        migrations.RunPython(create_default_practitioner)
    ]
