# Generated by Django 3.1.6 on 2021-04-07 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persistence', '0006_auto_20210330_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='assigned_patients', to='persistence.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='family_members',
            field=models.ManyToManyField(null=True, related_name='relatives',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
