# Generated by Django 3.1.6 on 2021-04-17 21:14

import django.db.models.deletion
from django.db import migrations, models

from persistence.models import FuzzySetup


def create_fuzzy_setup(apps, schema_editor):
    fuzzy_setup = FuzzySetup.objects.create(
        universes_description={"step_asymmetry_seconds": {"range": [0, 0.31, 0.01],
                                                          "membership_functions": [
                                                              {"label": "normal",
                                                               "type": "triangle",
                                                               "points": [0, 0, 0.02]},
                                                              {"label": "abnormal",
                                                               "type": "triangle",
                                                               "points": [0.01, 0.04, 0.1]},
                                                              {"label": "bad", "type": "trapezoid",
                                                               "points": [0.08, 0.12, 0.31,
                                                                          0.31]}]},
                               "stride_seconds": {"range": [0, 2.0, 0.01], "membership_functions": [
                                   {"label": "fast", "type": "triangle", "points": [0, 0, 0.8]},
                                   {"label": "normal", "type": "trapezoid",
                                    "points": [0.7, 0.9, 1, 1.15]},
                                   {"label": "slow", "type": "trapezoid",
                                    "points": [1.05, 1.5, 2.0, 2.0]}]},
                               "stance_seconds": {"range": [0, 1.5, 0.01], "membership_functions": [
                                   {"label": "short", "type": "triangle", "points": [0, 0, 0.52]},
                                   {"label": "normal", "type": "trapezoid",
                                    "points": [0.48, 0.55, 0.6, 0.67]},
                                   {"label": "lengthy", "type": "trapezoid",
                                    "points": [0.6, 0.8, 0.9, 1.1]},
                                   {"label": "long", "type": "trapezoid",
                                    "points": [1.0, 1.25, 1.5, 1.5]}]},
                               "swing_seconds": {"range": [0, 0.7, 0.01], "membership_functions": [
                                   {"label": "short", "type": "trapezoid",
                                    "points": [0, 0, 0.2, 0.36]},
                                   {"label": "normal", "type": "triangle",
                                    "points": [0.3, 0.35, 0.42]},
                                   {"label": "long", "type": "trapezoid",
                                    "points": [0.36, 0.55, 0.7, 0.7]}]},
                               "stance_percentage": {"range": [0, 1, 0.01],
                                                     "membership_functions": [
                                                         {"label": "low", "type": "trapezoid",
                                                          "points": [0, 0, 0.45, 0.6]},
                                                         {"label": "normal", "type": "trapezoid",
                                                          "points": [0.55, 0.58, 0.62, 0.65]},
                                                         {"label": "high", "type": "trapezoid",
                                                          "points": [0.6, 0.7, 1, 1]}]},
                               "swing_percentage": {"range": [0, 1, 0.01], "membership_functions": [
                                   {"label": "low", "type": "trapezoid",
                                    "points": [0, 0, 0.31, 0.4]},
                                   {"label": "normal", "type": "trapezoid",
                                    "points": [0.35, 0.38, 0.42, 0.45]},
                                   {"label": "high", "type": "trapezoid",
                                    "points": [0.4, 0.45, 1, 1]}]},
                               "double_support_percentage": {"range": [0, 1, 0.01],
                                                             "membership_functions": [
                                                                 {"label": "low",
                                                                  "type": "trapezoid",
                                                                  "points": [0, 0, 0.15, 0.21]},
                                                                 {"label": "normal",
                                                                  "type": "triangle",
                                                                  "points": [0.18, 0.21, 0.24]},
                                                                 {"label": "elevated",
                                                                  "type": "trapezoid",
                                                                  "points": [0.21, 0.3, 0.35, 0.4]},
                                                                 {"label": "high",
                                                                  "type": "trapezoid",
                                                                  "points": [0.33, 0.42, 1, 1]}]}},
        rules=["If step_asymmetry_seconds are normal then user_score is good",
               "If step_asymmetry_seconds are abnormal then user_score is average",
               "If step_asymmetry_seconds are bad then user_score is bad",
               "If double_support_percentage is low then user_score is average",
               "If double_support_percentage is normal then user_score is good",
               "If double_support_percentage is elevated then user_score is average",
               "If double_support_percentage is high then user_score is bad",
               "If stance_percentage is low or swing_percentage is low then user_score is bad",
               "If stance_percentage is normal or swing_percentage is normal then user_score is good",
               "If stance_percentage is high or swing_percentage is high then user_score is bad",
               "If stance_seconds are normal or swing_seconds are normal or stride_seconds are not slow then user_score is good",
               "If stance_seconds are lengthy or swing_seconds are short or stride_seconds are not normal then user_score is bad",
               "If stance_seconds are long or swing_seconds are long or stride_seconds are fast then user_score is bad",
               "If stance_seconds are short or stride_seconds are normal then user_score is average",
               "If stride_seconds are slow then user_score is average"],
        patient_id=None
    )
    fuzzy_setup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('persistence', '0007_patient_assigned_practitioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('universes_description', models.JSONField()),
                ('rules', models.JSONField()),
                ('patient',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='persistence.patient')),
            ],
        ),
        migrations.AddField(
            model_name='activityresult',
            name='preprocessing_result',
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(create_fuzzy_setup)
    ]
