# Generated by Django 3.1.6 on 2021-04-17 21:14

import django.db.models.deletion
from django.db import migrations, models

from persistence.models import FuzzySetup


def create_fuzzy_setup(apps, schema_editor):
    fuzzy_setup = FuzzySetup.objects.create(
        universes_description={"step_asymmetry_seconds": {"range": [0, 0.31, 0.01],
                                                          "membership_functions": [
                                                              {"label": "normal",
                                                               "type": "triangle",
                                                               "points": [0, 0, 0.02]},
                                                              {"label": "abnormal",
                                                               "type": "triangle",
                                                               "points": [0.01, 0.04, 0.08]},
                                                              {"label": "worrying",
                                                               "type": "triangle",
                                                               "points": [0.01, 0.04, 0.08]}]}},
        rules=["If step_asymmetry_seconds is normal then user_score is good",
               "If step_asymmetry_seconds is worrying then user_score is average"],
        patient_id=None
    )
    fuzzy_setup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('persistence', '0007_patient_assigned_practitioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('universes_description', models.JSONField()),
                ('rules', models.JSONField()),
                ('patient',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='persistence.patient')),
            ],
        ),
        migrations.AddField(
            model_name='activityresult',
            name='preprocessing_result',
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(create_fuzzy_setup)
    ]
